<?php

namespace App\Services;

class SeedCreatorProfileCatalog
{
    public function all(): array
    {
        $recommenders = [
            ['Amina Diallo', 'Investor', true],
            ['Tomiwa Adeyemi', 'Founder', true],
            ['Nandi Mokoena', 'Operator', true],
            ['Brian Mwangi', 'Researcher', true],
            ['Esi Mensah', 'Journalist', false],
            ['Karim Hassan', 'Policy', true],
        ];

        $rec = function (int $index, string $snippet, string $date) use ($recommenders): array {
            [$name, $role, $verified] = $recommenders[$index % count($recommenders)];

            return compact('name', 'role', 'verified', 'snippet', 'date');
        };

        return [
            $this->profile('benjamin-dada', 'Benjamin Dada', 'Publication tracking African startups, funding, product launches, and ecosystem operators.', 'https://www.benjamindada.com/', ['Pan-African', 'Nigeria'], ['Startups', 'Venture', 'Fintech'], ['Publication', 'Newsletter'], [$rec(0, 'Consistent operator-level reporting with useful funding context.', '2026-04-21'), $rec(1, 'Good first stop when I need to know what actually shipped.', '2026-03-17'), $rec(2, 'The archive is searchable and less hype-driven than most startup media.', '2026-01-12')], 'Approved', '2026-04-21'),
            $this->profile('africa-the-big-deal', 'Africa: The Big Deal', 'Data-led publication on African startup funding, deal flow, and investor trends.', 'https://thebigdeal.substack.com/', ['Pan-African'], ['Funding', 'Venture', 'Data'], ['Newsletter', 'Research'], [$rec(3, 'Best recurring funding dataset for board decks and market notes.', '2026-05-02'), $rec(0, 'Their charts make funding cycles legible without extra theater.', '2026-02-03'), $rec(5, 'Useful because they publish methodology and caveats.', '2025-12-08')], 'Approved', '2026-05-02'),
            $this->profile('techcabal', 'TechCabal', 'Pan-African tech publication covering startups, policy, telecoms, fintech, and digital culture.', 'https://techcabal.com/', ['Pan-African', 'Nigeria'], ['Startups', 'Policy', 'Fintech', 'Telecoms'], ['Publication', 'Newsletter'], [$rec(4, 'Broadest daily read for ecosystem movement across markets.', '2026-04-15'), $rec(2, 'Strong on the intersection of regulation and startup execution.', '2026-03-03'), $rec(1, 'Useful signal for founders trying to understand market narratives.', '2025-11-19')], 'Approved', '2026-04-15'),
            $this->profile('rest-of-world-africa', 'Rest of World: Africa', 'Reported stories on technology, labor, platforms, and startup consequences across African markets.', 'https://restofworld.org/region/africa/', ['Pan-African'], ['Platforms', 'Policy', 'Labor', 'Startups'], ['Publication', 'Research'], [$rec(4, 'Context-rich reporting that catches second-order effects.', '2026-02-22'), $rec(5, 'Good counterweight to pure funding optimism.', '2025-10-10')], 'Approved', '2026-02-22'),
            $this->profile('disrupt-africa', 'Disrupt Africa', 'Startup publication and reports covering African founders, funding rounds, and ecosystem rankings.', 'https://disrupt-africa.com/', ['Pan-African'], ['Startups', 'Funding', 'Reports'], ['Publication', 'Research'], [$rec(0, 'Useful long-running archive of funding and company updates.', '2026-01-28'), $rec(3, 'The annual reports are handy baselines for market sizing.', '2025-12-11')], 'Approved', '2026-01-28'),
            $this->profile('techpoint-africa', 'Techpoint Africa', 'Media company covering African startup news, founder stories, events, and product launches.', 'https://techpoint.africa/', ['Nigeria', 'Pan-African'], ['Startups', 'Founders', 'Products'], ['Publication', 'YouTube', 'Newsletter'], [$rec(1, 'Practical interviews and early signals from Nigerian founders.', '2026-04-03'), $rec(2, 'Good coverage of company-building details, not just funding.', '2025-12-17')], 'Approved', '2026-04-03'),
            $this->profile('wee-tracker', 'WeeTracker', 'African startup intelligence platform focused on funding, exits, and ecosystem research.', 'https://weetracker.com/', ['Pan-African'], ['Funding', 'Market Intel', 'Venture'], ['Publication', 'Research', 'Database'], [$rec(3, 'Useful for market maps and historical transaction checks.', '2026-02-14'), $rec(0, 'Their data lens helps separate momentum from noise.', '2025-11-05')], 'Approved', '2026-02-14'),
            $this->profile('magnitt-africa', 'MAGNiTT Africa', 'Venture data platform with Africa and MENA funding dashboards, reports, and investor data.', 'https://magnitt.com/', ['North Africa', 'Pan-African'], ['Venture', 'Data', 'MENA', 'Funding'], ['Research', 'Database'], [$rec(0, 'Strong for North Africa and MENA comparison work.', '2026-03-30'), $rec(5, 'Helpful when validating funding claims against a broader dataset.', '2026-01-09')], 'Approved', '2026-03-30'),
            $this->profile('afridigest', 'Afridigest', 'Curated briefing on African technology, business, and macro signals.', 'https://afridigest.com/', ['Pan-African'], ['Business', 'Startups', 'Macro'], ['Newsletter'], [$rec(2, 'Concise enough for weekly reading, broad enough to spot themes.', '2026-04-09'), $rec(1, 'Good curation layer for investors with limited context windows.', '2026-01-20')], 'Approved', '2026-04-09'),
            $this->profile('briter-bridges', 'Briter Bridges', 'Market intelligence and visual maps of African startup ecosystems, investors, and sectors.', 'https://briterbridges.com/', ['Pan-African'], ['Market Maps', 'Venture', 'Ecosystems'], ['Research', 'Database'], [$rec(3, 'Their maps are an efficient way to understand sector structure.', '2026-04-18'), $rec(0, 'Good for explaining ecosystem density to non-local partners.', '2025-12-04'), $rec(2, 'Useful source for duplicate detection and company clustering.', '2025-09-29')], 'Approved', '2026-04-18'),
            $this->profile('african-tech-roundup', 'African Tech Roundup', 'Podcast and analysis platform on African technology, media, policy, and venture dynamics.', 'https://africantechroundup.com/', ['Pan-African', 'South Africa'], ['Venture', 'Policy', 'Media'], ['Podcast', 'Newsletter'], [$rec(1, 'Good long-form analysis when headlines are too thin.', '2026-03-13'), $rec(5, 'Connects regulation, operators, and capital in one conversation.', '2025-10-31')], 'Approved', '2026-03-13'),
            $this->profile('the-flip', 'The Flip', 'Podcast on African startups, venture capital, and operating lessons from emerging markets.', 'https://theflip.africa/', ['Pan-African'], ['Venture', 'Founders', 'Markets'], ['Podcast', 'Newsletter'], [$rec(0, 'Founder and investor conversations with unusually strong context.', '2026-04-26'), $rec(1, 'Good for learning how specific African business models work.', '2026-02-16'), $rec(2, 'The episode notes make it useful beyond audio.', '2025-12-22')], 'Approved', '2026-04-26'),
            $this->profile('founders-factory-africa-blog', 'Founders Factory Africa Insights', 'Operator essays and venture-building notes from an Africa-focused startup studio and investor.', 'https://www.foundersfactory.africa/insights', ['Pan-African', 'South Africa'], ['Venture Building', 'Climate', 'Healthtech'], ['Publication', 'Research'], [$rec(2, 'Good operator writing on venture building mechanics.', '2026-03-25'), $rec(0, 'Useful lens into what accelerators actually support post-investment.', '2025-11-14')], 'Needs Review', '2026-03-25'),
            $this->profile('ventures-platform', 'Ventures Platform Notes', 'Investor perspective on African early-stage startups, policy, and portfolio themes.', 'https://www.venturesplatform.com/', ['Nigeria', 'Pan-African'], ['Venture', 'Policy', 'Fintech'], ['Newsletter', 'LinkedIn'], [$rec(0, 'Clear investor perspective from a high-volume early-stage fund.', '2026-04-05'), $rec(1, 'Helpful for understanding what institutional seed capital values.', '2026-01-18')], 'Needs Review', '2026-04-05'),
            $this->profile('future-africa', 'Future Africa', 'Investor platform sharing thesis notes, founder resources, and African venture perspectives.', 'https://www.future.africa/', ['Nigeria', 'Pan-African'], ['Venture', 'Founders', 'Angel Investing'], ['Newsletter', 'LinkedIn'], [$rec(1, 'Strong signal from a networked fund and angel community.', '2026-02-28'), $rec(0, 'Useful for seeing how local capital formation is evolving.', '2025-12-02')], 'Approved', '2026-02-28'),
            $this->profile('partech-africa-reports', 'Partech Africa Reports', 'Annual and thematic reports on venture funding across African technology markets.', 'https://partechpartners.com/africa/', ['Pan-African', 'Francophone'], ['Funding', 'Venture', 'Data'], ['Research'], [$rec(3, 'Institutional benchmark for annual funding comparisons.', '2026-01-31'), $rec(5, 'Good source when public deal data needs triangulation.', '2025-11-22')], 'Approved', '2026-01-31'),
            $this->profile('africa-fintech-network', 'Africa Fintech Network', 'Industry network and publication surface for fintech policy, market updates, and ecosystem convening.', 'https://africafintechnetwork.com/', ['Pan-African'], ['Fintech', 'Policy', 'Payments'], ['Community', 'Publication'], [$rec(5, 'Good policy and association signal for fintech regulation.', '2026-03-08'), $rec(2, 'Useful for separating fintech adoption from licensing reality.', '2025-12-19')], 'Needs Review', '2026-03-08'),
            $this->profile('iafrikan', 'iAfrikan', 'Technology publication covering digital policy, privacy, platforms, and African internet culture.', 'https://iafrikan.com/', ['South Africa', 'Pan-African'], ['Policy', 'Privacy', 'Telecoms'], ['Publication'], [$rec(5, 'Useful for rights, privacy, and policy context often missed elsewhere.', '2026-02-07'), $rec(4, 'Good archive on internet infrastructure and digital regulation.', '2025-10-13')], 'Approved', '2026-02-07'),
            $this->profile('appsafrica', 'AppsAfrica', 'Media and awards platform tracking African mobile, venture, and technology companies.', 'https://www.appsafrica.com/', ['Pan-African'], ['Mobile', 'Startups', 'Awards'], ['Publication', 'Community'], [$rec(2, 'Good discovery layer for mobile-first companies and awards finalists.', '2026-01-16'), $rec(4, 'Useful for surfacing less-covered regional products.', '2025-09-20')], 'Approved', '2026-01-16'),
            $this->profile('startup-list-africa', 'StartupList Africa', 'Directory of African startups, accelerators, investors, and ecosystem programs.', 'https://www.startuplist.africa/', ['Pan-African'], ['Directories', 'Startups', 'Investors'], ['Database'], [$rec(3, 'Helpful reference when checking whether a company is already indexed.', '2026-04-11'), $rec(1, 'Good lightweight directory for ecosystem navigation.', '2025-12-28')], 'Approved', '2026-04-11'),
            $this->profile('launch-base-africa', 'Launch Base Africa', 'Newsletter and research surface for African startup launches, tools, and founder resources.', 'https://www.launchbaseafrica.com/', ['Pan-African'], ['Startups', 'Tools', 'Founders'], ['Newsletter', 'Database'], [$rec(1, 'Good early discovery of products before they hit larger media.', '2026-03-19'), $rec(2, 'Helpful for founders tracking comparable launches.', '2025-11-03')], 'Needs Review', '2026-03-19'),
            $this->profile('michael-kimani', 'Michael Kimani', 'Kenyan tech operator and writer covering crypto, fintech, startups, and ecosystem development.', 'https://www.linkedin.com/in/michael-kimani/', ['Kenya', 'East Africa'], ['Crypto', 'Fintech', 'Startups'], ['LinkedIn', 'Newsletter'], [$rec(1, 'Strong ground-level perspective on East African fintech and crypto.', '2026-04-30'), $rec(0, 'Good mix of policy context and operator reality.', '2026-02-01')], 'Approved', '2026-04-30'),
            $this->profile('oo-nwoye', 'Oo Nwoye', 'Operator and ecosystem commentator sharing sharp notes on Nigerian startups and technology markets.', 'https://www.linkedin.com/in/oonwoye/', ['Nigeria'], ['Startups', 'Operators', 'Product'], ['LinkedIn'], [$rec(1, 'Operator commentary with a strong filter for incentives.', '2026-04-24'), $rec(2, 'Useful for understanding what builders say off-stage.', '2026-01-26')], 'Approved', '2026-04-24'),
            $this->profile('maya-horgan-famodu', 'Maya Horgan Famodu', 'Investor voice on African venture capital, founder markets, and capital allocation.', 'https://www.linkedin.com/in/mayahorganfamodu/', ['Nigeria', 'Pan-African'], ['Venture', 'Investing', 'Founders'], ['LinkedIn'], [$rec(0, 'Useful investor signal from early-stage Africa venture.', '2026-03-27'), $rec(1, 'Strong on what founders need from cross-border capital.', '2025-12-15')], 'Approved', '2026-03-27'),
            $this->profile('victor-asemota', 'Victor Asemota', 'Technology investor and operator sharing direct analysis on African startups and market structure.', 'https://www.linkedin.com/in/victorasemota/', ['Nigeria', 'Pan-African'], ['Venture', 'Strategy', 'Infrastructure'], ['LinkedIn'], [$rec(1, 'High-signal commentary on market structure and founder incentives.', '2026-05-01'), $rec(0, 'Good for uncomfortable but useful ecosystem truths.', '2026-02-18'), $rec(2, 'Often identifies weak assumptions before they become consensus.', '2025-12-30')], 'Approved', '2026-05-01'),
            $this->profile('rebecca-enonchong', 'Rebecca Enonchong', 'Founder, investor, and policy advocate with commentary on African technology ecosystems.', 'https://www.linkedin.com/in/rebeccaenonchong/', ['Pan-African', 'Francophone'], ['Policy', 'Founders', 'Venture'], ['LinkedIn'], [$rec(5, 'Strong bridge between founders, policy, and Francophone Africa.', '2026-04-07'), $rec(0, 'Credible because the perspective is earned across markets.', '2026-01-04')], 'Approved', '2026-04-07'),
            $this->profile('eloho-omame', 'Eloho Omame', 'Investor and ecosystem builder writing about venture capital, gender, and African startup growth.', 'https://www.linkedin.com/in/elohoomame/', ['Nigeria', 'Pan-African'], ['Venture', 'Gender', 'Founders'], ['LinkedIn', 'Newsletter'], [$rec(0, 'Thoughtful VC perspective with a useful inclusion lens.', '2026-03-06'), $rec(2, 'Good signal for pre-seed founder support and ecosystem gaps.', '2025-11-18')], 'Approved', '2026-03-06'),
            $this->profile('ken-njoroge', 'Ken Njoroge', 'Founder and investor voice on payments, scaling, and East African technology markets.', 'https://www.linkedin.com/in/kennjoroge/', ['Kenya', 'East Africa'], ['Fintech', 'Scaling', 'Founders'], ['LinkedIn'], [$rec(1, 'Rare founder perspective on payments at real scale.', '2026-02-26'), $rec(2, 'Useful when thinking about East African market expansion.', '2025-12-09')], 'Approved', '2026-02-26'),
            $this->profile('mest-africa', 'MEST Africa', 'Training and ecosystem platform sharing founder programs, startup spotlights, and pan-African events.', 'https://meltwater.org/', ['Ghana', 'Pan-African'], ['Founders', 'Training', 'Ecosystems'], ['Community', 'Publication'], [$rec(2, 'Good signal for early founder pipelines and program alumni.', '2026-02-12'), $rec(4, 'Helpful for Ghana and pan-African accelerator context.', '2025-10-22')], 'Needs Review', '2026-02-12'),
            $this->profile('kola-aina', 'Kola Aina', 'Investor and founder voice on early-stage African startups, capital, and operator networks.', 'https://www.linkedin.com/in/kolaaina/', ['Nigeria', 'Pan-African'], ['Venture', 'Founders', 'Capital'], ['LinkedIn'], [$rec(0, 'High-context investor view from repeated early-stage exposure.', '2026-04-14'), $rec(1, 'Useful for understanding what strong local lead investors look for.', '2026-01-08')], 'Approved', '2026-04-14'),
            $this->profile('africarena', 'AfricArena', 'Ecosystem platform publishing startup challenges, reports, and investor convening across Africa.', 'https://www.africarena.com/', ['Pan-African', 'South Africa'], ['Venture', 'Events', 'Startups'], ['Community', 'Research'], [$rec(4, 'Good way to discover challenge-stage startups across regions.', '2026-03-11'), $rec(0, 'Useful convening signal, especially for investor-founder matching.', '2025-11-27')], 'Approved', '2026-03-11'),
            $this->profile('techcabal-dupe', 'Tech Cabal', 'Potential duplicate spelling for TechCabal; included to show moderation merge handling.', 'https://techcabal.com/', ['Pan-African'], ['Startups', 'Policy'], ['Publication'], [$rec(4, 'Same source appears under a spaced spelling in the thread.', '2026-04-16')], 'Duplicate', '2026-04-16', 'techcabal'),
        ];
    }

    private function profile(string $id, string $name, string $bio, string $link, array $geography, array $topics, array $formats, array $recommendations, string $status, string $lastSeen, ?string $duplicateOf = null): array
    {
        return [
            'id' => $id,
            'name' => $name,
            'bio' => $bio,
            'link' => $link,
            'geography' => $geography,
            'topics' => $topics,
            'formats' => $formats,
            'recommendations' => $recommendations,
            'status' => $status,
            'last_seen' => $lastSeen,
            'duplicate_of' => $duplicateOf,
        ];
    }
}
